[project]
name = "django-weather"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.7",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]
